# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='type',
            field=models.CharField(default='misc', max_length=100),
        ),
    ]
