# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_challenge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='solved',
            field=models.IntegerField(default=0),
        ),
    ]
